   [[redirects]]
     from = "/api/*"
     to = "https://flipkart-clone-backend-esb4.onrender.com/api/:splat"
     status = 200
     force = true

   [[redirects]]
     from = "/*"
     to = "/index.html"
     status = 200
